---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.appName }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.backend.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.appName }}
    spec:
      containers:
      - name: {{ .Values.backend.appName }}
        image: {{ .Values.backend.imageName }}:{{ .Values.backend.imageTag }}
        envFrom:
        - secretRef:
            name: ciso-backend-secret
        - configMapRef:
            name: ciso-backend-config
        lifecycle:
          postStart:
            exec:
              command:
              - "sh"
              - "-c"
              - |
                sleep 20
                python -c 'import django; django.setup(); from iam.models import User; User.objects.create_superuser("$DJANGO_SUPERUSER_EMAIL", "$DJANGO_SUPERUSER_PASSWORD")' || true
