---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.appName }} 
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.frontend.appName }} 
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
